tap "anomalyco/tap"
tap "nikitabobko/tap"

# review tooling, also installed as pinned binaries on Linux by install-cli-tools.sh
brew "neovim"
brew "lazygit"
brew "git-delta"
brew "tuicr"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "tree-sitter-cli"

brew "gh"
brew "git-lfs"
brew "jq"
brew "htop"
brew "wget"
brew "pandoc"
brew "qrencode"
brew "scc"
brew "imagemagick"
brew "zellij"
brew "anomalyco/tap/opencode", trusted: true

brew "go"
brew "python@3.13"
brew "uv"
brew "pipx"
brew "nox"
brew "pnpm"
brew "rbenv"
brew "cmake"
brew "meson"

brew "podman"
brew "grpcurl"
brew "stern"

brew "cocoapods"
brew "xcodegen"
brew "ios-deploy"
brew "libimobiledevice"
brew "yubico-piv-tool"

cask "kitty"
cask "ghostty"
cask "font-jetbrains-mono"
cask "aerospace"
cask "rectangle"
cask "scroll-reverser"
cask "keyboard-maestro"
cask "lunar"

cask "cursor"
cask "claude"
cask "neovide-app"
cask "tableplus"
cask "openlens"
cask "obsidian"

cask "ungoogled-chromium"
cask "microsoft-edge"
cask "transmit"
cask "transmission"
cask "outline-manager"
cask "spotify"
cask "vlc"
