
" Vim TextEditor Configuration
" Gadzhi Gadzhiev <gadzhi@gadzhiev.com>
" https://github.com/resure/dotfiles
set nocompatible

filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'mileszs/ack.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'slack/vim-bufexplorer'
Bundle 'kien/ctrlp.vim'

" Bundle 'scrooloose/syntastic'
Bundle 'ctags.vim'
" Bundle 'airblade/vim-gitgutter'

Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-eunuch'
Bundle 'mattn/gist-vim'

Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"
Bundle "honza/vim-snippets"

Bundle 'tpope/vim-dispatch'

" Bundle 'bling/vim-airline'
" Bundle 'edkolev/tmuxline.vim'

Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-rails'
" Bundle 'tpope/vim-markdown'
Bundle 'plasticboy/vim-markdown'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-git'
Bundle 'leafgarland/typescript-vim'
Bundle 'groenewege/vim-less'
Bundle 'kchmck/vim-coffee-script'
Bundle 'mintplant/vim-literate-coffeescript'
Bundle 'sickill/vim-pasta'
Bundle 'slim-template/vim-slim'
Bundle 'wlangstroth/vim-haskell'
Bundle 'pangloss/vim-erlang'
Bundle 'csexton/jekyll.vim'
Bundle 'digitaltoad/vim-jade'
Bundle 'wting/rust.vim'
Bundle 'mustache/vim-mustache-handlebars'
Bundle 'jnwhiteh/vim-golang'

" Bundle 'vim-scripts/guicolorscheme.vim'
Bundle 'flazz/vim-colorschemes'
Bundle 'sjl/badwolf'
Bundle 'chriskempson/vim-tomorrow-theme'
Bundle 'dhruvasagar/vim-railscasts-theme'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tomasr/molokai'

filetype plugin indent on         " Required for Vundle
syntax enable

set nowrap                        " Don't wrap lines
set scrolloff=7                   " Show 3 lines of context around the cursor.
set tabstop=2 shiftwidth=2        " A tab is two spaces
set expandtab                     " Use spaces, not tabs
set backspace=indent,eol,start    " Backspace through everything in insert mode

set modelines=0                   " Preventing some security exploits.

" set nobackup                      " Don't make a backup before overwriting a file.

set backupdir=~/.vim/_backup      " Where to put backup files.
set directory=~/.vim/_temp        " Where to put swap files.

set showcmd                       " Display incomplete commands and mode you're in
set showmode

set linespace=4                   " Add some line space for easy reading.

set visualbell                    " Disable visual bell.

set encoding=utf-8                " Set main encoding.

set autoindent

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest

set title                         " Set the terminal's title.
set ttyfast                       " Indicates a fast terminal connection.

set ruler                         " Show the current line and column number.
set number                        " Show line numbers.

set laststatus=2                  " Show the status line all the time.
hi StatusLine ctermbg=white ctermfg=darkblue
hi StatusLineNC ctermbg=black ctermfg=grey
highlight Search ctermfg=White ctermbg=Blue

set ignorecase                    " Case-sensitive search.
set smartcase

set gdefault                      " Applying substitutions globally on lines.

set incsearch                     " Highlighting search results.
set showmatch
set hlsearch

"set wrap                         " Making Vim handle long lines correctly.
"set textwidth=79
"set linebreak
"set formatoptions=qrn1
"set colorcolumn=85

" set list                          " Better invisible characters.
set listchars=tab:▸\ ,eol:¬

set mouse=a                       " Some stuff to get the mouse going in term.
set ttymouse=xterm2

set splitbelow
set splitright
set wildmenu
set wildmode=list:longest,full


let mapleader = ","               " Setup leader key.

" Switch invisible characters
map <leader>i :set list!<CR>

" Delete all trailing whitespacces
map <leader>u :%s/\s\+$//<CR>

" Easier commands
nnoremap ; :
vnoremap ; :

" Turning off vim's regex chars
nnoremap / /\v
vnoremap / /\v

nnoremap <leader>a :Ack

" Re-hardwrap paragraphs of text
nnoremap <leader>q gqip

" Reselect pasted text
nnoremap <leader>v V`]

" Quicker Escaping
inoremap jj <ESC>

" Working with split windows
nnoremap <leader>g <C-w>v<C-w>l
nnoremap <leader>s <C-w>s<C-w>l

" Navigating around the splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" NERDTree keys.
silent! nmap <silent> <Leader>p :NERDTreeToggle<CR>
nnoremap <silent> <C-f> :call FindInNERDTree()<CR>

" Map to bufexplorer
nnoremap <leader>e :BufExplorer<cr>

" Tab mappings
map <leader>tt :tabnew<CR>
map <leader>te :tabedit
map <leader>tc :tabclose<CR>
map <leader>to :tabonly<CR>
map <leader>tn :tabnext<CR>
map <leader>tp :tabprevious<CR>
map <leader>tf :tabfirst<CR>
map <leader>tl :tablast<CR>
map <leader>tm :tabmove

" vim-gitgutter
map <leader>tg :GitGutterToggle<CR>
" let g:gitgutter_enabled = 0

" ctrlp.vim
map <leader>f :CtrlPMixed<CR>

" Clear out a search
nnoremap <leader><space> :noh<cr>

" GUI
set antialias
set mouse=a
set guioptions-=T " no toolbar set guioptions-=m " no menus
set guioptions-=r " no scrollbar on the right
set guioptions-=R " no scrollbar on the right
set guioptions-=l " no scrollbar on the left
set guioptions-=b " no scrollbar on the bottom
set guioptions=aiA
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=
set gfn=DejaVu\ Sans\ Mono\ 11

" Russian key maps
source ~/.vim/russian

" Fast switch between two last files
nnoremap <leader><leader> <c-^>

" gist-vim
let g:gist_open_browser_after_post = 1
let g:gist_post_private = 1
let g:gist_detect_filetype = 1

" mustache
let g:mustache_abbreviations = 1

" literate coffeescript
autocmd FileType litcoffee runtime ftplugin/coffee.vim

" custom syntax highlighting
au BufRead,BufNewFile {Capfile,Gemfile,Rakefile,Thorfile,bluepill.pill,config.ru,.caprc,.irbrc,irb_tempfile*} set ft=ruby

" turn off default mode indicator
" set noshowmode

set ruf=%32(%l\ %c\ [%Y/%{&ff}/%{strlen(&fenc)?&fenc:'none'}]\ %p%%%)

