
#############
# Functions #
#############

source "$HOME/.zsh/defuns"

#########
# Theme #
#########

source "$HOME/.zsh/colors"



###########
# Aliases #
###########

source "$HOME/.zsh/aliases"



##########
# Config #
##########

source "$HOME/.zsh/config"



##############
# Completion #
##############

source "$HOME/.zsh/completion"

